import Head from "next/head";
import { Inter } from "next/font/google";
import { Chip } from "@/components/chips";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={inter.style}>
        <header>
          <h1>Brittany Chiang</h1>

          <br />

          <Chip>JavaScript</Chip>
          <Chip>JavaScript</Chip>
          <Chip>JavaScript</Chip>
          <Chip>JavaScript</Chip>

          <div>
            1
          </div>
          <div>
            1
          </div>
          <div>
            1
          </div>
          <div>
            1
          </div>
        </header>
      </div>
    </>
  );
}
